### ISSUE TITLE
Support for Jenkins

### ISSUE THREAD

**Issue by dbedrenko** [Lectem/cpp-boilerplate#10]
Hi, great repo! I'm learning a lot. 

Would be good if Jenkins was also supported. This is a very popular CI tool.

**Comment by Lectem** [comment]
This is not really in my plans, but any PR is welcome.
It should be as easy as using the following script though : 
```sh
cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && \
make -j4 && \
ctest -VV .
```
