### ISSUE TITLE
Running the build and documentation for it

### ISSUE THREAD

**Issue by evenstensberg** [Lectem/cpp-boilerplate#19]
Hi!  I'm quite new to cmake, but I tried to run `cmake .` after bootstrapping the project. It showed an error from here:

`
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_BINARY_DIR)
    message(FATAL_ERROR "Do not build in-source. Please remove CMakeCache.txt and the CMakeFiles/ directory. Then build out-of-source.")
endif()`

Is there any installation instructions of how to build?

**Comment by Lectem** [comment]
Hi !
It is recommended to put the build directory out of source.
This can be done by starting cmake from a subdirectory you created (for example `build`) with `cmake ..` or simply indicate the build directory using the following:

```sh
# configure the project
cmake -B build
# build the project
cmake --build build
```

For more information about CMake basics you can have a look at https://www.siliceum.com/en/blog/post/cmake_01_cmake-basics/

**Comment by evenstensberg** [comment]
Th!
